<<<<<<< HEAD
services:
  inventory-service:
    build: .
    container_name: accesorios-dm-inventory-service-prod
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://accesorios-dm-postgres-prod:5432/accesorios_dm_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SERVER_PORT=8080
    networks:
      - accesorios-dm-net

networks:
  accesorios-dm-net:
    external: true
    name: accesorios-dm-database_accesorios-network-prod
=======
version: "3.9"

services:
  inventory-service:
    build: .
    container_name: accesorios-inventory-service
    restart: always
    ports:
      - "8082:8082"
    environment:
      - DB_URL=jdbc:postgresql://host.docker.internal:5432/accesorios_dm?currentSchema=catalogo,inventario
      - DB_USERNAME=svc_inventory
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=8082
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - accesorios-network

networks:
  accesorios-network:
    external: true
    name: accesorios-network
>>>>>>> b4883ed0b5faca54e1ebb9465472557e808ca36f
