spring.application.name=com.accesoriosdm.inventory
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/accesoriosdm_inventory
spring.datasource.username=accesoriosdm
spring.datasource.password=accesoriosdm
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false