spring:
  application:
    name: inventory-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/accesorios_dm_db?currentSchema=catalogo,inventario}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

  liquibase:
    enabled: false

server:
  port: ${PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.accesoriosdm.inventory: DEBUG
